In [24]:
import pandas as pd

In [26]:
df = pd.read_csv("player_detections.csv")
df.iloc[100:150]

     frame  id           x1          y1           x2          y2
100     27   2   452.895447  666.327515   635.726074  835.816223
101     27   4   921.601318   53.515614   954.497070  131.876221
102     27   6  1492.503662  684.176331  1674.477783  876.202942
103     28   1   835.325989  144.023758   888.266541  244.477631
104     28   2   451.316223  666.012390   639.695923  835.154846
105     28   4   922.072998   54.046722   954.451599  131.939651
106     28   6  1486.211914  683.363159  1674.767700  872.979431
107     29   1   833.150635  143.523712   886.638000  244.912094
108     29   2   450.364899  665.719299   639.882935  834.817139
109     29   4   919.872437   54.445011   954.691528  132.011108
110     29   6  1484.080811  682.777954  1674.781494  871.483032
111     30   1   829.531921  143.253479   884.320740  242.359863
112     30   2   450.313843  665.697937   637.766052  834.298279
113     30   4   911.120117   55.101288   954.735596  131.958908
114     30   6  1485.437256  682.092346  1673.903687  870.930664
115     31   1   825.658875  142.710892   878.393127  241.367554
116     31   2   450.324036  665.649475   633.027344  833.962708
117     31   4   914.603210   55.394722   954.701660  131.961823
118     31   6  1486.184937  681.586182  1673.086060  871.159546
119     32   1   822.045227  142.431778   873.977600  241.740250
120     32   2   451.204926  665.654968   631.700928  833.789856
121     32   4   913.630310   55.334156   954.650879  131.853073
122     32   6  1486.097290  681.342834  1672.090332  871.014465
123     33   1   819.011414  142.324722   868.042664  241.261368
124     33   2   452.117065  665.647522   632.377625  833.860229
125     33   4   913.477783   55.829746   954.672058  131.836456
126     33   6  1485.061523  680.629578  1671.427490  871.458191
127     34   1   814.906555  142.905518   864.380249  240.988556
128     34   2   452.521698  665.712280   633.763550  834.223206
129     34   4   921.142273   56.222858   955.006531  131.936493
130     34   6  1484.624634  679.832520  1670.219238  871.985168
131     35   1   804.702942  142.873627   861.693787  240.677353
132     35   2   452.894196  665.678162   629.575195  833.610596
133     35   4   917.818298   57.861481   954.952515  131.917603
134     35   6  1482.778687  679.784912  1668.208740  872.798950
135     35   8   453.808929  665.977112   588.673096  787.070679
136     36   1   795.095886  142.914795   858.928406  241.503647
137     36   4   921.620483   58.548515   955.288879  131.683441
138     36   6  1482.348022  678.651367  1666.398560  872.241455
139     36   8   454.162079  666.203125   594.235657  787.410156
140     37   1   783.170959  143.809799   858.239014  242.968842
141     37   4   924.290527   59.291199   957.037781  131.906708
142     37   6  1482.482178  678.377502  1663.781982  871.058960
143     37   8   453.907104  665.874023   596.035278  786.919922
144     38   1   771.662537  144.245300   858.356506  243.331482
145     38   4   925.652161   59.552135   957.960449  132.001205
146     38   6  1482.750610  678.418091  1660.475342  870.271301
147     38   2   453.584900  665.712830   605.921387  794.540649
148     39   1   766.163879  145.409302   859.670227  245.340988
149     39   4   925.809937   59.672234   958.665161  132.204788

In [21]:
df.value_counts('id')

id
1     371
4     367
2     361
6     352
12     12
8       3
20      2
18      1
Name: count, dtype: int64

In [22]:
top_four_ids = df['id'].value_counts().head(4).index
df.loc[~df['id'].isin(top_four_ids), 'id'] = pd.NA
df = df.iloc[100:150]
df

     frame   id           x1          y1           x2          y2
100     27  2.0   452.895447  666.327515   635.726074  835.816223
101     27  4.0   921.601318   53.515614   954.497070  131.876221
102     27  6.0  1492.503662  684.176331  1674.477783  876.202942
103     28  1.0   835.325989  144.023758   888.266541  244.477631
104     28  2.0   451.316223  666.012390   639.695923  835.154846
105     28  4.0   922.072998   54.046722   954.451599  131.939651
106     28  6.0  1486.211914  683.363159  1674.767700  872.979431
107     29  1.0   833.150635  143.523712   886.638000  244.912094
108     29  2.0   450.364899  665.719299   639.882935  834.817139
109     29  4.0   919.872437   54.445011   954.691528  132.011108
110     29  6.0  1484.080811  682.777954  1674.781494  871.483032
111     30  1.0   829.531921  143.253479   884.320740  242.359863
112     30  2.0   450.313843  665.697937   637.766052  834.298279
113     30  4.0   911.120117   55.101288   954.735596  131.958908
114     30  6.0  1485.437256  682.092346  1673.903687  870.930664
115     31  1.0   825.658875  142.710892   878.393127  241.367554
116     31  2.0   450.324036  665.649475   633.027344  833.962708
117     31  4.0   914.603210   55.394722   954.701660  131.961823
118     31  6.0  1486.184937  681.586182  1673.086060  871.159546
119     32  1.0   822.045227  142.431778   873.977600  241.740250
120     32  2.0   451.204926  665.654968   631.700928  833.789856
121     32  4.0   913.630310   55.334156   954.650879  131.853073
122     32  6.0  1486.097290  681.342834  1672.090332  871.014465
123     33  1.0   819.011414  142.324722   868.042664  241.261368
124     33  2.0   452.117065  665.647522   632.377625  833.860229
125     33  4.0   913.477783   55.829746   954.672058  131.836456
126     33  6.0  1485.061523  680.629578  1671.427490  871.458191
127     34  1.0   814.906555  142.905518   864.380249  240.988556
128     34  2.0   452.521698  665.712280   633.763550  834.223206
129     34  4.0   921.142273   56.222858   955.006531  131.936493
130     34  6.0  1484.624634  679.832520  1670.219238  871.985168
131     35  1.0   804.702942  142.873627   861.693787  240.677353
132     35  2.0   452.894196  665.678162   629.575195  833.610596
133     35  4.0   917.818298   57.861481   954.952515  131.917603
134     35  6.0  1482.778687  679.784912  1668.208740  872.798950
135     35  NaN   453.808929  665.977112   588.673096  787.070679
136     36  1.0   795.095886  142.914795   858.928406  241.503647
137     36  4.0   921.620483   58.548515   955.288879  131.683441
138     36  6.0  1482.348022  678.651367  1666.398560  872.241455
139     36  NaN   454.162079  666.203125   594.235657  787.410156
140     37  1.0   783.170959  143.809799   858.239014  242.968842
141     37  4.0   924.290527   59.291199   957.037781  131.906708
142     37  6.0  1482.482178  678.377502  1663.781982  871.058960
143     37  NaN   453.907104  665.874023   596.035278  786.919922
144     38  1.0   771.662537  144.245300   858.356506  243.331482
145     38  4.0   925.652161   59.552135   957.960449  132.001205
146     38  6.0  1482.750610  678.418091  1660.475342  870.271301
147     38  2.0   453.584900  665.712830   605.921387  794.540649
148     39  1.0   766.163879  145.409302   859.670227  245.340988
149     39  4.0   925.809937   59.672234   958.665161  132.204788

In [23]:
# Fill missing ids by matching each NaN bbox to the closest bbox in the previous frame
def bbox_center(row):
    return ((row["x1"] + row["x2"]) / 2, (row["y1"] + row["y2"]) / 2)

nan_mask = df["id"].isna()

for idx, row in df.loc[nan_mask].iterrows():
    prev_frame = row["frame"] - 1
    prev_rows = df[(df["frame"] == prev_frame) & df["id"].notna()]
    
    if prev_rows.empty:
        continue
    
    cx, cy = bbox_center(row)
    prev_centers = prev_rows.apply(bbox_center, axis=1)
    distances = ((prev_centers.apply(lambda p: p[0]) - cx) ** 2 + (prev_centers.apply(lambda p: p[1]) - cy) ** 2) ** 0.5
    
    closest_idx = distances.idxmin()
    df.at[idx, "id"] = df.at[closest_idx, "id"]

df

     frame   id           x1          y1           x2          y2
100     27  2.0   452.895447  666.327515   635.726074  835.816223
101     27  4.0   921.601318   53.515614   954.497070  131.876221
102     27  6.0  1492.503662  684.176331  1674.477783  876.202942
103     28  1.0   835.325989  144.023758   888.266541  244.477631
104     28  2.0   451.316223  666.012390   639.695923  835.154846
105     28  4.0   922.072998   54.046722   954.451599  131.939651
106     28  6.0  1486.211914  683.363159  1674.767700  872.979431
107     29  1.0   833.150635  143.523712   886.638000  244.912094
108     29  2.0   450.364899  665.719299   639.882935  834.817139
109     29  4.0   919.872437   54.445011   954.691528  132.011108
110     29  6.0  1484.080811  682.777954  1674.781494  871.483032
111     30  1.0   829.531921  143.253479   884.320740  242.359863
112     30  2.0   450.313843  665.697937   637.766052  834.298279
113     30  4.0   911.120117   55.101288   954.735596  131.958908
114     30  6.0  1485.437256  682.092346  1673.903687  870.930664
115     31  1.0   825.658875  142.710892   878.393127  241.367554
116     31  2.0   450.324036  665.649475   633.027344  833.962708
117     31  4.0   914.603210   55.394722   954.701660  131.961823
118     31  6.0  1486.184937  681.586182  1673.086060  871.159546
119     32  1.0   822.045227  142.431778   873.977600  241.740250
120     32  2.0   451.204926  665.654968   631.700928  833.789856
121     32  4.0   913.630310   55.334156   954.650879  131.853073
122     32  6.0  1486.097290  681.342834  1672.090332  871.014465
123     33  1.0   819.011414  142.324722   868.042664  241.261368
124     33  2.0   452.117065  665.647522   632.377625  833.860229
125     33  4.0   913.477783   55.829746   954.672058  131.836456
126     33  6.0  1485.061523  680.629578  1671.427490  871.458191
127     34  1.0   814.906555  142.905518   864.380249  240.988556
128     34  2.0   452.521698  665.712280   633.763550  834.223206
129     34  4.0   921.142273   56.222858   955.006531  131.936493
130     34  6.0  1484.624634  679.832520  1670.219238  871.985168
131     35  1.0   804.702942  142.873627   861.693787  240.677353
132     35  2.0   452.894196  665.678162   629.575195  833.610596
133     35  4.0   917.818298   57.861481   954.952515  131.917603
134     35  6.0  1482.778687  679.784912  1668.208740  872.798950
135     35  2.0   453.808929  665.977112   588.673096  787.070679
136     36  1.0   795.095886  142.914795   858.928406  241.503647
137     36  4.0   921.620483   58.548515   955.288879  131.683441
138     36  6.0  1482.348022  678.651367  1666.398560  872.241455
139     36  2.0   454.162079  666.203125   594.235657  787.410156
140     37  1.0   783.170959  143.809799   858.239014  242.968842
141     37  4.0   924.290527   59.291199   957.037781  131.906708
142     37  6.0  1482.482178  678.377502  1663.781982  871.058960
143     37  2.0   453.907104  665.874023   596.035278  786.919922
144     38  1.0   771.662537  144.245300   858.356506  243.331482
145     38  4.0   925.652161   59.552135   957.960449  132.001205
146     38  6.0  1482.750610  678.418091  1660.475342  870.271301
147     38  2.0   453.584900  665.712830   605.921387  794.540649
148     39  1.0   766.163879  145.409302   859.670227  245.340988
149     39  4.0   925.809937   59.672234   958.665161  132.204788